# Generated by Django 3.2.5 on 2021-10-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquirys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('message', models.TextField()),
                ('joining_date', models.DateField()),
                ('When', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
