# Generated by Django 3.2.5 on 2021-10-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('expiry_package', models.DateTimeField(auto_now=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
