# Generated by Django 3.2.5 on 2021-10-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_enquirys_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirys',
            name='When',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='enquirys',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
