# Generated by Django 3.2.5 on 2021-10-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20211028_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirys',
            name='When',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
