# Generated by Django 3.2.5 on 2021-10-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_alter_enquirys_when'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquirys',
            options={'ordering': ['-updated', '-When']},
        ),
        migrations.AddField(
            model_name='enquirys',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enquirys',
            name='When',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
