# Generated by Django 3.2.5 on 2021-10-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20211028_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquirys',
            options={},
        ),
        migrations.RemoveField(
            model_name='enquirys',
            name='updated',
        ),
    ]
