# Generated by Django 3.2.5 on 2021-10-28 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20211028_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirys',
            name='timming',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
