# Generated by Django 3.2.5 on 2021-10-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_enquirys_visit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirys',
            name='visit_type',
            field=models.CharField(blank=True, choices=[('Call', 'c'), ('Directly', 'd')], max_length=10),
        ),
    ]
