# Generated by Django 3.2.5 on 2021-08-07 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
